repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        files: \.(ts|tsx|js|jsx|json)$

      - id: eslint
        name: ESLint
        entry: npx eslint --fix
        language: system
        files: \.(ts|tsx|js|jsx)$

      - id: type-check
        name: TypeScript
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$

      - id: tests
        name: Tests
        entry: npm test -- --bail --findRelatedTests --passWithNoTests
        language: system
        files: \.(ts|tsx)$
